const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const c=vm.createContext({Blob,TextEncoder,TextDecoder,Uint8Array,DataView,Map,setTimeout});vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/export.js'),'utf8'),c);
(async()=>{c.original=new Uint8Array([0,255,12,45,128]);const zip=vm.runInContext("packBackupZip([['campaigns.json',new TextEncoder().encode('{\"ok\":true}')],['maps/map-0.bin',original]])",c);c.buffer=await zip.arrayBuffer();const map=vm.runInContext('unpackBackupZip(buffer)',c);assert.deepEqual([...map.get('maps/map-0.bin')],[0,255,12,45,128]);assert.equal(new TextDecoder().decode(map.get('campaigns.json')),'{"ok":true}');const bad=c.buffer.slice(0);new Uint8Array(bad)[45]^=1;c.bad=bad;assert.throws(()=>vm.runInContext('unpackBackupZip(bad)',c));
Object.assign(c,{BACKUP_FORMAT:'fantasy-route-mapper',CURRENT_BACKUP_VERSION:1,APP_VERSION:'test',prepareCampaignData:d=>d});
c.records=[{id:'a',data:{},imageBlob:new Blob(['shared'])},{id:'b',data:{},imageBlob:new Blob(['shared'])}];
const shared=await vm.runInContext('makeBinaryBackup(records)',c);c.sharedBuffer=await shared.arrayBuffer();
const sharedFiles=vm.runInContext('unpackBackupZip(sharedBuffer)',c);assert.equal(sharedFiles.size,2);
const manifest=JSON.parse(new TextDecoder().decode(sharedFiles.get('campaigns.json')));assert.equal(manifest.campaigns[0].imageFile,manifest.campaigns[1].imageFile);
const root=path.join(__dirname,'..');const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');const assets=JSON.parse(sw.match(/const ASSETS=(\[.*?\]);/s)[1]);for(const a of assets)assert(fs.existsSync(path.join(root,a.split('?')[0])),a);for(const n of [192,512,180]){const png=fs.readFileSync(path.join(root,`assets/app-${n}.png`));assert.equal(png.readUInt32BE(16),n);assert.equal(png.readUInt32BE(20),n)}console.log('PASS binary ZIP roundtrip and corruption rejection, offline asset inventory and app-icon dimensions');})().catch(e=>{console.error(e);process.exit(1)});
